version: '3'
services:
  local-db:
    image: library/mysql:5.7
    container_name: local-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: kyle1234
      MYSQL_DATABASE: subway
      MYSQL_USER: cupeanimus
      MYSQL_PASSWORD: cupeanimus
      TZ: Asia/Seoul
    volumes:
      - /Users/kyle/datadir:/var/lib/mysql
